### ISSUE TITLE
Direct link to filtered people page not working

### ISSUE THREAD

**Issue by pwrstudio** [eyebeam-org/web#10]

**Comment by hobg0blin** [comment]
@pwrstudio what's the issue here? seems like linking to a specific alphabet number works but it's not adding a hash for things like artist/year

**Comment by pwrstudio** [comment]
What I want to do is being able to toggle the filter with a url, something like this:
https://eyebeam.netlify.app/people#artist
... which doesn't work right now.
It would be better to do it without using the hashes as well, as they are used for navigating between the letters.
I think I will assign myself to this issue as well – as I am a bit unclear what needs to be done!

**Comment by hobg0blin** [comment]
would something like this work? https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/URLSearchParams
