### ISSUE TITLE
Profile info tooltips cut off

### ISSUE THREAD

**Issue by pwrstudio** [eyebeam-org/web#14]
<img width="442" alt="Screenshot 2022-03-08 at 15 46 19" src="https://user-images.githubusercontent.com/8209990/158564191-6ed722b2-7d5a-49b7-b5ff-dabfd76f59b6.png">

**Comment by hobg0blin** [comment]
@pwrstudio this seems fixed on firefox/chrome on my machine -- did you already get to it?

**Comment by pwrstudio** [comment]
Yes, seems to work for me as well. I have noticed the dev server ("yarn dev") sometimes messing up the layout when hot reloading changes. This might have been the case here. Will close this for now.
