### ISSUE TITLE
direct linking with #filters (e.g. /everything#note) doesn't show the filter

### ISSUE THREAD

**Issue by hobg0blin** [eyebeam-org/web#21]
if you go directly to something like `/everything#note` it shows everything, not just notes

**Comment by hobg0blin** [comment]
@pwrstudio might be tied to this other issue (https://github.com/eyebeam-org/web/issues/10) but wanted to flag it in case

**Comment by pwrstudio** [comment]
Yes, you are right. Fundamentally the same as #10. I will look at both of these now...
